version: '3'

services:
  appronto-postgres:
    image: postgres
    environment:
      POSTGRES_USER: "appronto"
      POSTGRES_PASSWORD: "appronto"
    ports:
      - "5432:5432"
    # volumes:
    #   - appronto-postgres:/data_appronto_db
    networks:
      - appronto


networks:
  appronto:
    driver: bridge

